
services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1 
    volumes:
      - shared_data:/data
      - ./web:/app
    depends_on:
      - worker

  worker:
    build: ./worker
    volumes:
      - shared_data:/data
      - kraken_db:/human_viral_db
    deploy:
      replicas: 1

volumes:
  shared_data:
  kraken_db: